---
- hosts: k8sCluster
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - include_tasks: tasks/vagrant-setup.yml
      when: kubernetes_role == 'master'
 
  roles:
    - geerlingguy.security
    - geerlingguy.swap
    - geerlingguy.docker
    - geerlingguy.kubernetes

  tasks:
  - name: Printing Fact Variables                                         
    debug:                                                                
      msg: "The value of OS Family is {{ansible_os_family}}"   



  - name: Install Packages
    apt:
      name: 
      - python3-pip
      - curl
      state: present

  - name: Copy admin.conf to temp location
    ansible.builtin.copy:
      remote_src: yes
      src: /etc/kubernetes/admin.conf
      dest: /tmp/config.{{ cluster_name }}
    when: kubernetes_role == 'master'

  - name: Rename kubernetes-admin to cluster_name-admin
    ansible.builtin.replace:
      path: /tmp/config.{{ cluster_name }}
      regexp: 'kubernetes-admin'
      replace: "{{ cluster_name }}-admin"
    when: kubernetes_role == 'master'

  - name: Fetch the file from the master to ansible
    run_once: yes
    fetch: 
      src: /tmp/config.{{ cluster_name }}
      dest: "~/.kube/config.{{ cluster_name }}"
      flat: yes
    when: kubernetes_role == 'master'
